In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r"C:\Users\user\Downloads\hospitality.xlsx")

In [3]:
df.head()

,Booking id,Guest name,Room type,Service used,Location,Booking channel,Status,Check in date,Check out date,Night stayes,...,Guest country,Adults,Children,Total guest,Purpose of visit,Guest type,Payment method,Review category,Operating cost,Profit
0,B0001,Isha Khan,SUTE,SPA,Bangalore,Agent,Confirmed,2026-04-11,2026-04-13,2,...,Australia,1,2,3,Family,New,UPI,Average,708.05,346.95
1,B0002,Rahul Sharma,Deluxe,spa,Hyderabad,Agent,Confirmed,2025-08-17,2025-08-24,7,...,USA,1,2,3,Leisure,Returning,UPI,Average,331.93,388.07
2,B0003,Rahul Khan,SUTE,room service,Hyderabad,OTA,Confirmed,2025-10-01,2025-10-06,5,...,USA,3,1,4,Family,New,UPI,Good,251.78,173.22
3,B0004,Neha Gupta,DLX,Tour,Pune,website,Pending,2025-06-03,2025-06-05,2,...,Singapore,2,0,2,Leisure,Returning,Cash,Average,215.95,176.05
4,B0005,Arjun Verma,standard,SPA,Pune,website,Cancelled,2026-03-15,2026-03-21,6,...,India,2,0,2,Business,Returning,Debit Card,Excellent,461.84,174.16

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1080 entries, 0 to 1079
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Booking id        1080 non-null   str
 1   Guest name        1046 non-null   str
 2   Room type         1045 non-null   str
 3   Service used      935 non-null    str
 4   Location          1048 non-null   str
 5   Booking channel   1080 non-null   str
 6   Status            1080 non-null   str
 7   Check in date     1080 non-null   datetime64[us]
 8   Check out date    1080 non-null   str
 9   Night stayes      1080 non-null   int64
 10  Guest rating      1007 non-null   float64
 11  Room rating       1030 non-null   float64
 12  Total revenue     1030 non-null   float64
 13  Month year        1080 non-null   str
 14  Guest id          1080 non-null   str
 15  Age               1080 non-null   int64
 16  Gender            1080 non-null   str
 17  Guest country     1080 non-null   str
 18  Adults            1080 non-null   int64
 19  Children          1080 non-null   int64
 20  Total guest       1080 non-null   int64
 21  Purpose of visit  1080 non-null   str
 22  Guest type        1080 non-null   str
 23  Payment method    1080 non-null   str
 24  Review category   1007 non-null   str
 25  Operating cost    1030 non-null   float64
 26  Profit            1030 non-null   float64
dtypes: datetime64[us](1), float64(5), int64(5), str(16)
memory usage: 227.9 KB

In [5]:
df.isnull().sum()

Booking id            0
Guest name           34
Room type            35
Service used        145
Location             32
Booking channel       0
Status                0
Check in date         0
Check out date        0
Night stayes          0
Guest rating         73
Room rating          50
Total revenue        50
Month year            0
Guest id              0
Age                   0
Gender                0
Guest country         0
Adults                0
Children              0
Total guest           0
Purpose of visit      0
Guest type            0
Payment method        0
Review category      73
Operating cost       50
Profit               50
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df["Guest name"] = df["Guest name"].str.strip()

In [9]:
df["Guest name"] = df["Guest name"].str.title()
df

,Booking id,Guest name,Room type,Service used,Location,Booking channel,Status,Check in date,Check out date,Night stayes,...,Guest country,Adults,Children,Total guest,Purpose of visit,Guest type,Payment method,Review category,Operating cost,Profit
0,B0001,Isha Khan,SUTE,SPA,Bangalore,Agent,Confirmed,2026-04-11,2026-04-13,2,...,Australia,1,2,3,Family,New,UPI,Average,708.05,346.95
1,B0002,Rahul Sharma,Deluxe,spa,Hyderabad,Agent,Confirmed,2025-08-17,2025-08-24,7,...,USA,1,2,3,Leisure,Returning,UPI,Average,331.93,388.07
2,B0003,Rahul Khan,SUTE,room service,Hyderabad,OTA,Confirmed,2025-10-01,2025-10-06,5,...,USA,3,1,4,Family,New,UPI,Good,251.78,173.22
3,B0004,Neha Gupta,DLX,Tour,Pune,website,Pending,2025-06-03,2025-06-05,2,...,Singapore,2,0,2,Leisure,Returning,Cash,Average,215.95,176.05
4,B0005,Arjun Verma,standard,SPA,Pune,website,Cancelled,2026-03-15,2026-03-21,6,...,India,2,0,2,Business,Returning,Debit Card,Excellent,461.84,174.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075,B0864,Neha Khan,Standard,Breakfast,Bangalore,OTA,confirmed,2025-04-15,2025-04-17,2,...,UAE,2,2,4,Vacation,Returning,UPI,Average,NaN,NaN
1076,B0293,Neha Singh,delux,spa,Mumbai,OTA,Pending,2026-06-30,2026-07-01,1,...,India,1,2,3,Business,New,UPI,Good,1234.69,858.31
1077,B0165,Rohan Joshi,DLX,Tour,Mumbai,Direct,Cancelled,2026-01-15,2026-01-22,7,...,Australia,3,0,3,Business,Returning,Cash,Good,659.03,520.97
1078,B0994,Sana Gupta,suite,Tour,Hyderabad,OTA,Pending,2025-04-20,2025-04-24,4,...,Singapore,1,2,3,Family,Returning,Cash,Average,428.48,459.52
1079,B0531,Anaya Singh,delux,spa,Pune,website,Pending,2026-06-29,2026-07-06,7,...,UK,2,0,2,Family,New,Credit Card,Average,1235.96,498.04

In [10]:
df["Room type"].unique()

<StringArray>
[    'SUTE',   'Deluxe',      'DLX', 'standard',   'suite ',      'STD',
    'delux', 'Standard',    'Suite',        nan]
Length: 10, dtype: str

In [11]:
df["Room type"] = df["Room type"].replace({
    "STD": "Standard",
    "standard": "Standard",
    "suite ": "Suite",
    "SUTE": "Suite",
    "delux": "Deluxe",
    "DLX": "Deluxe"
})

In [12]:
df["Room type"].unique()

<StringArray>
['Suite', 'Deluxe', 'Standard', nan]
Length: 4, dtype: str

In [13]:
df["Service used"].unique()

<StringArray>
['SPA', 'spa', 'room service', 'Tour', nan, 'Breakfast', 'Room Service']
Length: 7, dtype: str

In [14]:
df["Service used"] = df["Service used"].replace({
    "spa": "SPA",
    "room service": "Room Service"
})

In [15]:
df["Service used"].unique()

<StringArray>
['SPA', 'Room Service', 'Tour', nan, 'Breakfast']
Length: 5, dtype: str

In [16]:
df["Location"].unique()

<StringArray>
['Bangalore', 'Hyderabad', 'Pune', 'Goa', 'Delhi', 'Mumbai', nan]
Length: 7, dtype: str

In [17]:
df["Booking channel"].unique()

<StringArray>
['Agent', 'OTA', 'website', 'Direct', 'Website']
Length: 5, dtype: str

In [18]:
df["Booking channel"] = df["Booking channel"].replace({
    "website": "Website"
})

In [19]:
df["Booking channel"].unique()

<StringArray>
['Agent', 'OTA', 'Website', 'Direct']
Length: 4, dtype: str

In [20]:
df["Status"].unique()

<StringArray>
['Confirmed', 'Pending', 'Cancelled', 'confirmed']
Length: 4, dtype: str

In [21]:
df["Status"] = df["Status"].replace({
    "confirmed": "Confirmed"
})

In [22]:
df["Status"].unique()

<StringArray>
['Confirmed', 'Pending', 'Cancelled']
Length: 3, dtype: str

In [23]:
df

,Booking id,Guest name,Room type,Service used,Location,Booking channel,Status,Check in date,Check out date,Night stayes,...,Guest country,Adults,Children,Total guest,Purpose of visit,Guest type,Payment method,Review category,Operating cost,Profit
0,B0001,Isha Khan,Suite,SPA,Bangalore,Agent,Confirmed,2026-04-11,2026-04-13,2,...,Australia,1,2,3,Family,New,UPI,Average,708.05,346.95
1,B0002,Rahul Sharma,Deluxe,SPA,Hyderabad,Agent,Confirmed,2025-08-17,2025-08-24,7,...,USA,1,2,3,Leisure,Returning,UPI,Average,331.93,388.07
2,B0003,Rahul Khan,Suite,Room Service,Hyderabad,OTA,Confirmed,2025-10-01,2025-10-06,5,...,USA,3,1,4,Family,New,UPI,Good,251.78,173.22
3,B0004,Neha Gupta,Deluxe,Tour,Pune,Website,Pending,2025-06-03,2025-06-05,2,...,Singapore,2,0,2,Leisure,Returning,Cash,Average,215.95,176.05
4,B0005,Arjun Verma,Standard,SPA,Pune,Website,Cancelled,2026-03-15,2026-03-21,6,...,India,2,0,2,Business,Returning,Debit Card,Excellent,461.84,174.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075,B0864,Neha Khan,Standard,Breakfast,Bangalore,OTA,Confirmed,2025-04-15,2025-04-17,2,...,UAE,2,2,4,Vacation,Returning,UPI,Average,NaN,NaN
1076,B0293,Neha Singh,Deluxe,SPA,Mumbai,OTA,Pending,2026-06-30,2026-07-01,1,...,India,1,2,3,Business,New,UPI,Good,1234.69,858.31
1077,B0165,Rohan Joshi,Deluxe,Tour,Mumbai,Direct,Cancelled,2026-01-15,2026-01-22,7,...,Australia,3,0,3,Business,Returning,Cash,Good,659.03,520.97
1078,B0994,Sana Gupta,Suite,Tour,Hyderabad,OTA,Pending,2025-04-20,2025-04-24,4,...,Singapore,1,2,3,Family,Returning,Cash,Average,428.48,459.52
1079,B0531,Anaya Singh,Deluxe,SPA,Pune,Website,Pending,2026-06-29,2026-07-06,7,...,UK,2,0,2,Family,New,Credit Card,Average,1235.96,498.04

In [24]:
df[["Check in date", "Check out date"]].isnull().sum()

Check in date     0
Check out date    0
dtype: int64

In [25]:
df["Night stayes"].isnull().sum()

np.int64(0)

In [26]:
df["Guest rating"].isnull().sum()

np.int64(73)

In [27]:
df["Guest rating"] = df["Guest rating"].fillna(df["Guest rating"].mean())

In [28]:
df["Review category"] = pd.cut(
    df["Guest rating"],
    bins=[0, 2.5, 3.5, 4.5, 5],
    labels=["Poor", "Average", "Good", "Excellent"]
)

In [29]:
df["Review category"].isnull().sum()

np.int64(0)

In [30]:
df["Room rating"].isnull().sum()

np.int64(50)

In [31]:
df["Room rating"] = df["Room rating"].fillna(df["Room rating"].mean())

In [32]:
df["Total revenue"].isnull().sum()

np.int64(50)

In [33]:
df["Total revenue"] = df["Total revenue"].fillna(
    df["Room rating"] * df["Night stayes"]
)

In [34]:
df["Total revenue"].isnull().sum()

np.int64(0)

In [35]:
df["Month year"].isnull().sum()

np.int64(0)

In [36]:
df["Room type"].isnull().sum()

np.int64(35)

In [37]:
df["Room type"] = df["Room type"].fillna("Unknown")

In [38]:
df["Location"].isnull().sum()

np.int64(32)

In [39]:
df["Location"] = df["Location"].fillna("Unknown")

In [40]:
df.head()

,Booking id,Guest name,Room type,Service used,Location,Booking channel,Status,Check in date,Check out date,Night stayes,...,Guest country,Adults,Children,Total guest,Purpose of visit,Guest type,Payment method,Review category,Operating cost,Profit
0,B0001,Isha Khan,Suite,SPA,Bangalore,Agent,Confirmed,2026-04-11,2026-04-13,2,...,Australia,1,2,3,Family,New,UPI,Average,708.05,346.95
1,B0002,Rahul Sharma,Deluxe,SPA,Hyderabad,Agent,Confirmed,2025-08-17,2025-08-24,7,...,USA,1,2,3,Leisure,Returning,UPI,Average,331.93,388.07
2,B0003,Rahul Khan,Suite,Room Service,Hyderabad,OTA,Confirmed,2025-10-01,2025-10-06,5,...,USA,3,1,4,Family,New,UPI,Good,251.78,173.22
3,B0004,Neha Gupta,Deluxe,Tour,Pune,Website,Pending,2025-06-03,2025-06-05,2,...,Singapore,2,0,2,Leisure,Returning,Cash,Average,215.95,176.05
4,B0005,Arjun Verma,Standard,SPA,Pune,Website,Cancelled,2026-03-15,2026-03-21,6,...,India,2,0,2,Business,Returning,Debit Card,Excellent,461.84,174.16

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1080 entries, 0 to 1079
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Booking id        1080 non-null   str
 1   Guest name        1046 non-null   str
 2   Room type         1080 non-null   str
 3   Service used      935 non-null    str
 4   Location          1080 non-null   str
 5   Booking channel   1080 non-null   str
 6   Status            1080 non-null   str
 7   Check in date     1080 non-null   datetime64[us]
 8   Check out date    1080 non-null   str
 9   Night stayes      1080 non-null   int64
 10  Guest rating      1080 non-null   float64
 11  Room rating       1080 non-null   float64
 12  Total revenue     1080 non-null   float64
 13  Month year        1080 non-null   str
 14  Guest id          1080 non-null   str
 15  Age               1080 non-null   int64
 16  Gender            1080 non-null   str
 17  Guest country     1080 non-null   str
 18  Adults            1080 non-null   int64
 19  Children          1080 non-null   int64
 20  Total guest       1080 non-null   int64
 21  Purpose of visit  1080 non-null   str
 22  Guest type        1080 non-null   str
 23  Payment method    1080 non-null   str
 24  Review category   1080 non-null   category
 25  Operating cost    1030 non-null   float64
 26  Profit            1030 non-null   float64
dtypes: category(1), datetime64[us](1), float64(5), int64(5), str(15)
memory usage: 220.8 KB

In [42]:
df["Service used"].isnull().sum()

np.int64(145)

In [43]:
df["Service used"] = df["Service used"].fillna("No Service")

In [44]:
df["Guest name"].isnull().sum()

np.int64(34)

In [45]:
df["Guest name"] = df["Guest name"].fillna("Unknown Guest")

In [47]:
df["Operating cost"].isnull().sum()
df["Profit"].isnull().sum()

np.int64(50)

In [48]:
df["Operating cost"] = df["Operating cost"].fillna(
    df["Operating cost"].median()
)

In [49]:
df["Profit"] = (
    df["Total revenue"] - df["Operating cost"]
)

In [50]:
df["Operating cost"].isnull().sum()
df["Profit"].isnull().sum()

np.int64(0)

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1080 entries, 0 to 1079
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Booking id        1080 non-null   str
 1   Guest name        1080 non-null   str
 2   Room type         1080 non-null   str
 3   Service used      1080 non-null   str
 4   Location          1080 non-null   str
 5   Booking channel   1080 non-null   str
 6   Status            1080 non-null   str
 7   Check in date     1080 non-null   datetime64[us]
 8   Check out date    1080 non-null   str
 9   Night stayes      1080 non-null   int64
 10  Guest rating      1080 non-null   float64
 11  Room rating       1080 non-null   float64
 12  Total revenue     1080 non-null   float64
 13  Month year        1080 non-null   str
 14  Guest id          1080 non-null   str
 15  Age               1080 non-null   int64
 16  Gender            1080 non-null   str
 17  Guest country     1080 non-null   str
 18  Adults            1080 non-null   int64
 19  Children          1080 non-null   int64
 20  Total guest       1080 non-null   int64
 21  Purpose of visit  1080 non-null   str
 22  Guest type        1080 non-null   str
 23  Payment method    1080 non-null   str
 24  Review category   1080 non-null   category
 25  Operating cost    1080 non-null   float64
 26  Profit            1080 non-null   float64
dtypes: category(1), datetime64[us](1), float64(5), int64(5), str(15)
memory usage: 220.8 KB

In [55]:
df.to_csv("hospitality_cleaned_dataset.csv", index=False)